// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
	int n1, n2;
	n1 = 10;
	n2 = 20;
	swapValues(n1, n2);
	REQUIRE(n1 == 20);
	REQUIRE(n2 == 10);
}
TEST_CASE("Ex2", "[example]")
{
	int n1, n2, n3;
	n1 = 10;
	n2 = 20;
	n3 = 30;
	swapValues(n1, n2, n3);
	REQUIRE(n1 == 20);
	REQUIRE(n2 == 30);
	REQUIRE(n3 == 10);
}
TEST_CASE("Ex3", "[example]")
{
	int n1, n2, n3, n4;
	n1 = 10;
	n2 = 20;
	n3 = 30;
	n4 = 40;
	swapValues(n1, n2, n3, n4);
	REQUIRE(n1 == 40);
	REQUIRE(n2 == 30);
	REQUIRE(n3 == 20);
	REQUIRE(n4 == 10);
}